spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ledger
    username: ledger_user
    password: ledger_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: ledger-posting-system-forex
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: forex-transactions

# Logging settings
logging:
  level:
    root: WARN
    org:
      hibernate: WARN
      springframework:
        web: INFO
        kafka: DEBUG
