spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: kafka:9092

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

h2:
  console:
    enabled: true
    path: /h2-console
